### ISSUE TITLE
Similar Apple watch unlock problem for z390 m gaming

### ISSUE THREAD

**Issue by victorsun1986** [extric99/Hackintosh-Gigabyte-Z390-GAMING-X-i9-9900k-5700XT#1]
hi
i'm using the gigabyte z390 m gaming motherboard, and i have the same apple watch unlock problem.
i'm about to try to flash a beta version bios for my motherboard, shutdown the super i/o option, i hope this would work for me too.

wondering why this option could affect the apple watch unlock, i tried to set the serial port to com1 on my another hackintosh Dell Optiplex 7050, the unlock function works well no matter the serial port is disabled or not.

i hope if you could give me some tips on how the serial port option affect the apple watch unlock, and thanks a lot

**Comment by extric99** [comment]
I am not sure why this happens exactly but on multiple Gigabyte motherboards the same behaviour is reported.

**Comment by victorsun1986** [comment]
OK, i got it.
I will have a try. 
Thx.

**Comment by victorsun1986** [comment]
i fix it by using a modified bios, the apple watch unlock works now
thanks a lot, have a good day.

**Comment by victorsun1986** [comment]
the apple watch unlock fails again after everytime the hackintosh sleep or reboot,
if i check the "unlock with apple watch" option and check again, it will come back to work, then fail agian after sleep or reboot
have you ever come to this situation?

**Comment by victorsun1986** [comment]
mobo: z390 m gaming
cpu: intel i9900K
WIFI/BT: FV-T919

**Comment by extric99** [comment]
Hi the z390m is a different board than the Gaming X I am using so I can not help you here other than to suggest two things.
- make sure the usb is configured and mapped correctly. You can not use my mapping as it is specific to the Gaming X board
- log out completely of icloud and restart

Many people use this board on tonymacx86 including the admins so best to check in for board specific support there. There is a thread with a sample configuration published here
https://www.tonymacx86.com/threads/gigabyte-z390-m-gaming-build-with-working-nvram.291193/

**Comment by victorsun1986** [comment]
ok, i got it
thanks you very much
