### ISSUE TITLE
GPU option?

### ISSUE THREAD

**Issue by chengjk84** [extric99/Hackintosh-Gigabyte-Z390-GAMING-X-i9-9900k-5700XT#10]
Will this setting work with Gigabyte RX5600XT or RX5600? any1 use it?

**Comment by extric99** [comment]
Yes these cards are natively supported by macOS from Catalina 15.1. The optimisations AML file that I used in the EFI to get similar performance to a real Mac depend on the type of card:

The RX 5700 XT SSDT.aml works with RX 5600/5700/5700XT.
The RX 5500 XT SSDT.aml works with RX 5500/5500XT 

https://www.tonymacx86.com/threads/amd-radeon-performance-enhanced-ssdt.296555/

**Comment by chengjk84** [comment]
thanks for the info
