### ISSUE TITLE
蓝牙正常 wifi 无法使用

### ISSUE THREAD

**Issue by etscript** [extric99/Hackintosh-Gigabyte-Z390-GAMING-X-i9-9900k-5700XT#11]
您好，我用您分享的，我发现我的蓝牙是正常的。wifi无法使用。

配置除了显卡是580之外，和您的配置一致。

我还需要做另外的什么操作吗？

**Comment by CodingFishWu** [comment]
FV-T919是免驱的，应该不会出现wifi无法使用的情况吧
