### ISSUE TITLE
Bluetooth doesn't work after upgrading to Monterey

### ISSUE THREAD

**Issue by CodingFishWu** [extric99/Hackintosh-Gigabyte-Z390-GAMING-X-i9-9900k-5700XT#13]
I have updated MacOS to Monterey and OC to 0.7.9, everything works well except bluetooth. I use the same BT card with yours, as well as most other configurations.

I have read the issue #12 , and saw that you have tried upgrading to Monterey. Could you please share the EFI files to me? I can't salve this problem by myself.

Thanks!

**Comment by extric99** [comment]
Please use the latest release. It should solve the issue.

**Comment by CodingFishWu** [comment]
It works in my Monterey 12.3.1. Thanks so much!
And what's more, can you tell me how can I update my EFI in future? I have waited for this version for a long time.
Thanks again!
