### ISSUE TITLE
Many Thanks

### ISSUE THREAD

**Issue by BassVagal** [extric99/Hackintosh-Gigabyte-Z390-GAMING-X-i9-9900k-5700XT#14]
Had Same Build than you and I installed Big Sur with your EFI config 

Then I was able to upgrade Opencore to 0.8.3 with OCAuxiliary Tools and update via OTA from 11.5.2 to 12.5.1 without any prob. 

Thanks a lot for sharing!

**Comment by extric99** [comment]
You are welcome!
