### ISSUE TITLE
why you set XhciPortLimit false.

### ISSUE THREAD

**Issue by 44886** [extric99/Hackintosh-Gigabyte-Z390-GAMING-X-i9-9900k-5700XT#2]
it can use more USB

**Comment by extric99** [comment]
XhciPortLimit is used for setup when discovering all ports, not for daily use. Going above 15 ports can create corruption as per documentation. You are always welcome to experiment yourself with the setting and ssdt definition. 

https://dortania.github.io/OpenCore-Post-Install/usb/#macos-and-the-15-port-limit

**Comment by 44886** [comment]
thank you.
