### ISSUE TITLE
No output from GPU after (display) wake

### ISSUE THREAD

**Issue by jdek** [extric99/Hackintosh-Gigabyte-Z390-GAMING-X-i9-9900k-5700XT#4]
After 15 minutes when the display goes to sleep (see preferences below), I'm unable to wake it again. The machine is definitely awake as I'm able to log into it via SSH. Tried turning off/on display, switching inputs, etc. When I reboot the machine, the display activates to show the verbose shutdown log.

I haven't enabled CFG-LOCK in BIOS yet, could this be related? (I used the config.plist quirk to install macOS). I'm using a slightly different motherboard (Gigabyte Z390 Aorus Pro), so it's also likely there are other modifications I'm missing.

Would appreciate if you could point me in the right direction.

<img width="780" alt="Screen Shot 2020-11-16 at 02 38 51" src="https://user-images.githubusercontent.com/15961926/99204098-dec54980-27b4-11eb-8ef1-1d5b6956739c.png">

**Comment by extric99** [comment]
For help on other motherboards i suggest to visit https://www.tonymacx86.com/. Multiple people use this board and most likely have working EFI’s.

**Comment by jdek** [comment]
Alright. Thought maybe you were doing some extra configuration for sleep to work.

**Comment by extric99** [comment]
Try disabling standby
“sudo pmset -a standby 0“
