### ISSUE TITLE
ASRock Taichi Z390

### ISSUE THREAD

**Issue by dvlpmt** [extric99/Hackintosh-Gigabyte-Z390-GAMING-X-i9-9900k-5700XT#5]
Hi there,

Do you think I could try and use this configuration on my MB?

Thanks

**Comment by extric99** [comment]
You can use the EFi as a starting point but you will need to change it. The USB mappings will need to be updated and maybe some other kext used. Use the dortania guide to setup your EFI https://dortania.github.io/OpenCore-Post-Install/usb/
