### ISSUE TITLE
Can I update from 10.15.6 to 11.0.1 directly?

### ISSUE THREAD

**Issue by CodingFishWu** [extric99/Hackintosh-Gigabyte-Z390-GAMING-X-i9-9900k-5700XT#6]
My hardwares are completely same as yours. And I'm using your EFI files and everything goes well.
I'm using z390's Beta BIOS.

Can I update from 10.15.6 to 11.0.1 directly?

**Comment by extric99** [comment]
I updated myself from 15.7 to Big Sur and had no issues. There is a part of the upgrade process that takes quite some time and it looks like the upgrade hangs but this is normal. Just be patient as it can take 10m or more.
