### ISSUE TITLE
iMessage Not working

### ISSUE THREAD

**Issue by rahulmangla19** [extric99/Hackintosh-Gigabyte-Z390-GAMING-X-i9-9900k-5700XT#7]
i have the same Config and uses your EFI as Base and iMessage are not working. 
[Send me iMac.zip](https://github.com/extric99/Hackintosh-Gigabyte-Z390-GAMING-X-i9-9900k-5700XT/files/5622722/Send.me.iMac.zip)
kindly help in Big Sur

**Comment by extric99** [comment]
Many reasons why iMessage would not work but this is not related to the EFI itself.
You can try below and if this does not work I suggest to join tonymacx86.com to get some help there. 

To delete/reset Preferences:

Make sure you are signed out of all services and restart before beginning these steps.

Open Terminal
Enter sudo rm into Terminal to trigger password prompt if necessary.
Paste all at once into Terminal:
sudo rm -rf ~/Library/Caches/com.apple.iCloudHelper* \
            ~/Library/Caches/com.apple.Messages* \
            ~/Library/Caches/com.apple.imfoundation.IMRemoteURLConnectionAgent* \
            ~/Library/Preferences/com.apple.iChat* \
            ~/Library/Preferences/com.apple.icloud* \
            ~/Library/Preferences/com.apple.imagent* \
            ~/Library/Preferences/com.apple.imessage* \
            ~/Library/Preferences/com.apple.imservice* \
            ~/Library/Preferences/com.apple.ids.service* \
            ~/Library/Preferences/com.apple.madrid.plist* \
            ~/Library/Preferences/com.apple.imessage.bag.plist* \
            ~/Library/Preferences/com.apple.identityserviced* \
            ~/Library/Preferences/com.apple.ids.service* \
            ~/Library/Preferences/com.apple.security* \
            ~/Library/Messages
Reboot Hackintosh and check iMessage/iCloud/Facetime
