### ISSUE TITLE
iGPU?

### ISSUE THREAD

**Issue by chengjk84** [extric99/Hackintosh-Gigabyte-Z390-GAMING-X-i9-9900k-5700XT#8]
Will it work with intel internal iGPU? or Does this EFI work with other GC like RX5600XT or GT710?

**Comment by extric99** [comment]
The EFI is designed to work with an ATI dgpu and together with the igpu for decoding/encoding
It have not tested but it should require to reconfigure the plist for either igpu only or nVidia gpu’s. 
The RX5600XT should work fine as long as the bios is setup as specified and igpu turned on always

**Comment by chengjk84** [comment]
Thanks for the info...
